In [ ]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.layers import Dense, Dropout

In [ ]:
EPOCHS = 200
BATCH_SIZE = 4
VERBOSE = 1
NB_CLASSES = 3
N_HIDDEN = 64  # Increased the number of neurons
VALIDATION_SPLIT = 0.2

In [ ]:
data = pd.read_csv('/content/Credit Score Classification Dataset.csv')

In [ ]:
data_train, data_test = train_test_split(data, train_size=0.8, test_size=0.2, random_state=100)
xtrain = data_train.drop('Credit Score', axis=1)
ytrain = data_train['Credit Score']
xtest = data_test.drop('Credit Score', axis=1)
ytest = data_test['Credit Score']

In [ ]:
le = LabelEncoder()
ytrain = le.fit_transform(ytrain)
ytrain = tf.keras.utils.to_categorical(ytrain, num_classes=3)
ytest = le.transform(ytest)
ytest = tf.keras.utils.to_categorical(ytest, num_classes=3)


In [ ]:
xtrain = pd.get_dummies(xtrain, columns=['Gender', 'Education', 'Marital Status', 'Home Ownership'])
xtest = pd.get_dummies(xtest, columns=['Gender', 'Education', 'Marital Status', 'Home Ownership'])


In [ ]:
xtrain, xtest = xtrain.align(xtest, join='left', axis=1, fill_value=0)

In [ ]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [ ]:
model = tf.keras.models.Sequential()
model.add(Dense(N_HIDDEN, input_shape=(xtrain.shape[1],), activation='relu', name='denselayer0'))
model.add(Dropout(0.5))
model.add(Dense(N_HIDDEN, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(NB_CLASSES, activation='softmax', name='outputlayer'))

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(xtrain, ytrain, batch_size=BATCH_SIZE, epochs=EPOCHS, verbose=VERBOSE, validation_split=VALIDATION_SPLIT)

Epoch 1/200
26/26 [==============================] - 3s 48ms/step - loss: 0.8133 - accuracy: 0.6058 - val_loss: 0.5962 - val_accuracy: 0.8519
Epoch 2/200
26/26 [==============================] - 0s 5ms/step - loss: 0.5752 - accuracy: 0.7500 - val_loss: 0.4323 - val_accuracy: 0.8519
Epoch 3/200
26/26 [==============================] - 0s 8ms/step - loss: 0.4638 - accuracy: 0.8558 - val_loss: 0.3415 - val_accuracy: 0.8519
Epoch 4/200
26/26 [==============================] - 0s 12ms/step - loss: 0.4075 - accuracy: 0.8462 - val_loss: 0.3067 - val_accuracy: 0.8519
Epoch 5/200
26/26 [==============================] - 0s 6ms/step - loss: 0.3222 - accuracy: 0.8846 - val_loss: 0.2883 - val_accuracy: 0.8889
Epoch 6/200
26/26 [==============================] - 0s 7ms/step - loss: 0.2571 - accuracy: 0.9327 - val_loss: 0.2751 - val_accuracy: 0.8889
Epoch 7/200
26/26 [==============================] - 0s 7ms/step - loss: 0.2232 - accuracy: 0.9135 - val_loss: 0.2576 - val_accuracy: 0.8889
Epoch 8/200

In [ ]:
test_loss, test_acc = model.evaluate(xtest, ytest)
print('Test accuracy:', test_acc)


2/2 [==============================] - 0s 7ms/step - loss: 1.4390 - accuracy: 0.9091
Test accuracy: 0.9090909361839294


2/2 [==============================] - 0s 11ms/step
Predictions: [[8.41516391e-15 9.99999940e-01 5.31223982e-22]
 [1.82176542e-18 9.99999940e-01 8.98907489e-31]
 [8.43931973e-01 1.52144819e-01 3.92320519e-03]
 [9.99979198e-01 2.06901623e-05 2.64982064e-10]
 [3.15682799e-01 2.06140541e-02 6.63703084e-01]
 [7.15907585e-13 9.99999940e-01 2.54390527e-15]
 [5.13610530e-07 9.99999464e-01 7.63503011e-11]
 [3.03252161e-14 9.99999940e-01 2.87199706e-23]
 [3.15682799e-01 2.06140541e-02 6.63703084e-01]
 [1.16732296e-14 9.99999940e-01 1.57179349e-22]
 [5.05173847e-10 9.99999940e-01 2.49700591e-15]
 [2.15721885e-11 9.99999940e-01 4.02802452e-15]
 [3.26010811e-12 9.99999940e-01 1.03413355e-18]
 [8.29922140e-01 1.65231332e-01 4.84652584e-03]
 [1.13710846e-11 9.99999940e-01 1.58454983e-15]
 [7.77944393e-19 9.99999940e-01 1.89518418e-31]
 [2.47481285e-10 9.99999940e-01 9.69532652e-16]
 [7.36277705e-11 9.99999940e-01 7.82419512e-14]
 [1.37565835e-13 9.99999940e-01 4.07680385e-19]
 [9.99999702e-01 2.8697